include:
- template: Security/SAST.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: maven:3.9.5-amazoncorretto-21
  script:
    - pwd
    - mvn clean test



